name: Matt Frantz
favicon: null
layout_spectrum: 0.6021166644059122
typography_spectrum: 0.014965379144996405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.48502162797376513
purpose:
  - name: sign-ups
    item: null
    url: null
